<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Userrole extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Userrole_model');
    } 

    /*
     * Listing of userroles
     */
    function index()
    {
        $data['userroles'] = $this->Userrole_model->get_all_userroles();
        
        $data['_view'] = 'userrole/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new userrole
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'userRoleID' => $this->input->post('userRoleID'),
				'username' => $this->input->post('username'),
				'activityID' => $this->input->post('activityID'),
				'createdOn' => $this->input->post('createdOn'),
				'createdBy' => $this->input->post('createdBy'),
				'isDeleted' => $this->input->post('isDeleted'),
            );
            
            $userrole_id = $this->Userrole_model->add_userrole($params);
            redirect('userrole/index');
        }
        else
        {            
            $data['_view'] = 'userrole/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a userrole
     */
    function edit($id)
    {   
        // check if the userrole exists before trying to edit it
        $data['userrole'] = $this->Userrole_model->get_userrole($id);
        
        if(isset($data['userrole']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'userRoleID' => $this->input->post('userRoleID'),
					'username' => $this->input->post('username'),
					'activityID' => $this->input->post('activityID'),
					'createdOn' => $this->input->post('createdOn'),
					'createdBy' => $this->input->post('createdBy'),
					'isDeleted' => $this->input->post('isDeleted'),
                );

                $this->Userrole_model->update_userrole($id,$params);            
                redirect('userrole/index');
            }
            else
            {
                $data['_view'] = 'userrole/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The userrole you are trying to edit does not exist.');
    } 

    /*
     * Deleting userrole
     */
    function remove($id)
    {
        $userrole = $this->Userrole_model->get_userrole($id);

        // check if the userrole exists before trying to delete it
        if(isset($userrole['']))
        {
            $this->Userrole_model->delete_userrole($id);
            redirect('userrole/index');
        }
        else
            show_error('The userrole you are trying to delete does not exist.');
    }
    
}
