<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Useractivity extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Useractivity_model');
    } 

    /*
     * Listing of useractivities
     */
    function index()
    {
        $data['useractivities'] = $this->Useractivity_model->get_all_useractivities();
        
        $data['_view'] = 'useractivity/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new useractivity
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'activityID' => $this->input->post('activityID'),
				'activityName' => $this->input->post('activityName'),
				'isDeleted' => $this->input->post('isDeleted'),
            );
            
            $useractivity_id = $this->Useractivity_model->add_useractivity($params);
            redirect('useractivity/index');
        }
        else
        {            
            $data['_view'] = 'useractivity/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a useractivity
     */
    function edit($id)
    {   
        // check if the useractivity exists before trying to edit it
        $data['useractivity'] = $this->Useractivity_model->get_useractivity($id);
        
        if(isset($data['useractivity']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'activityID' => $this->input->post('activityID'),
					'activityName' => $this->input->post('activityName'),
					'isDeleted' => $this->input->post('isDeleted'),
                );

                $this->Useractivity_model->update_useractivity($id,$params);            
                redirect('useractivity/index');
            }
            else
            {
                $data['_view'] = 'useractivity/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The useractivity you are trying to edit does not exist.');
    } 

    /*
     * Deleting useractivity
     */
    function remove($id)
    {
        $useractivity = $this->Useractivity_model->get_useractivity($id);

        // check if the useractivity exists before trying to delete it
        if(isset($useractivity['']))
        {
            $this->Useractivity_model->delete_useractivity($id);
            redirect('useractivity/index');
        }
        else
            show_error('The useractivity you are trying to delete does not exist.');
    }
    
}
