<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Useractivity_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get useractivity by 
     */
    function get_useractivity($id)
    {
        return $this->db->get_where('useractivities',array(''=>$id))->row_array();
    }
        
    /*
     * Get all useractivities
     */
    function get_all_useractivities()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('useractivities')->result_array();
    }
        
    /*
     * function to add new useractivity
     */
    function add_useractivity($params)
    {
        $this->db->insert('useractivities',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update useractivity
     */
    function update_useractivity($id,$params)
    {
        $this->db->where('',$id);
        return $this->db->update('useractivities',$params);
    }
    
    /*
     * function to delete useractivity
     */
    function delete_useractivity($id)
    {
        return $this->db->delete('useractivities',array(''=>$id));
    }
}
