<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Userrole_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get userrole by 
     */
    function get_userrole($id)
    {
        return $this->db->get_where('userroles',array(''=>$id))->row_array();
    }
        
    /*
     * Get all userroles
     */
    function get_all_userroles()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('userroles')->result_array();
    }
        
    /*
     * function to add new userrole
     */
    function add_userrole($params)
    {
        $this->db->insert('userroles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update userrole
     */
    function update_userrole($id,$params)
    {
        $this->db->where('',$id);
        return $this->db->update('userroles',$params);
    }
    
    /*
     * function to delete userrole
     */
    function delete_userrole($id)
    {
        return $this->db->delete('userroles',array(''=>$id));
    }
}
